framework:
    rate_limiter:
        app:
            policy: 'sliding_window'
            limit: 500
            interval: '5 minutes'
        api:
            policy: 'sliding_window'
            limit: 5000
            interval: '5 minutes'
